### ISSUE TITLE
Handle adding distinct meta info for key

### ISSUE THREAD

**Issue by derekparker** [derekparker/trie#1]
Currently there is no way to append meta information for duplicate keys. This should be resolved by storing meta as []interface{}, and append meta for duplicate keys.

**Comment by ctrlrsf** [comment]
Any thoughts how this would be implemented? I imagine this might change existing Meta() API.

**Comment by derekparker** [comment]
Right, the `Meta` API would change since it would be returning a slice instead of a distinct piece of information.

As I think about this now, it might be possible, preferable even to put the impetus on the user and have the user store a slice as that meta value if they really need that functionality. This would not work directly with the `Add` method, you would need to `Find` first, and then set the meta yourself.

Do you have any thoughts or ideas on this?

**Comment by ctrlrsf** [comment]
I think leaving it up to the user is the right call. Changing `Meta` might not be worth it since it's already possible by just storing a slice as you mentioned.

When I first ran into the repo and saw this issue logged, I wondered why not just store a slice and came up with the simple test code below that showed it was possible.

Food for thought: Another approach if you did want the library to support distinct meta values is to allow a `Node` to store both a single meta value as it currently does, but also have a separate field such as `metaList`, that a few values could be pushed onto. Later they could be accessed by `MultiMeta()`, `MetaList()`, or what have you. Maybe even a bool `isMultiMeta`, that indicates whether the node is storing a single or multiple values. 

```
package main

import "fmt"
import "github.com/derekparker/trie"

func main() {
	t := trie.New()

	metalist := []string{"meta1", "meta2"}

	t.Add("foobar", metalist)

	node, _ := t.Find("foobar")
	meta := node.Meta()
	meta = append(meta.([]string), "meta3")

	fmt.Printf("Meta: %s\n", meta)
	// Output: Meta: [meta1 meta2 meta3]
}
```

**Comment by derekparker** [comment]
I'm going to close out this issue in favor of leaving it up to the user.
